### ISSUE TITLE
Setup public ip

### ISSUE THREAD

**Issue by Arshland35** [SniperOJ/Jeopardy-Dockerfiles#1]
how to setup in public ip ? please help me

**Comment by WangYihang** [comment]
Hi, bro
As you know, all challenges are supported by docker, so If you want to run a specific challenge and make it listen a public port, you can just change the `docker-compose.yml` file like this:
```
version: '2'

services:
    web:
        build: .
        ports:
            - '10008:80' // port 10008 will be the public port, and port 80 is the internal port
        stdin_open: true
        tty: true
        volumes:
            - ./source:/var/www/html
            - ./logs:/var/log/apache2
            - ./flag:/flag
```
